definitions:
  # Configure some default step values.
  step-defaults: &step-defaults
    timeout_in_minutes: 15
    retry:
      manual:
        permit_on_passed: true
  plugins:
    ecr: &ecr
      ecr#v2.0.0:
        login: true
        no-include-email: true

  # Specify common agent queue parameters.
  queues:
    # Docker-based tasks should run in the Docker queue.
    docker-agents: &docker-agents
      agents:
        queue: "docker-builders"
env:
  # If you do not declare buildkit:1 then arguments using for --target
  # do not work correctly and they will build every step.
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain

  # Identify the address for the shared Buildkite ECR repository.
  IMAGE_REPOSITORY: "165761832703.dkr.ecr.us-east-1.amazonaws.com"

  # Define a common namespace for images to be published within the shared ECR repo.
  ECR_NAMESPACE: "${IMAGE_REPOSITORY}/buildkite"


  # Define service directory where the Dockerfile is used.
  DOCKERFILE_LOCATION: "./"

  ARTIFACT_LOCATION: "./artifacts"
steps:
  - label: ":heavy_check_mark: :php: Lint PHPCS"
    key: "lint_phpcs"
    soft_fail:
      - exit_status: 1
    <<: *step-defaults
    <<: *docker-agents
    branches:
      - "!1.x"
      - "!main"
    commands:
      - 'echo "--- :docker: Build Docker Image"'
      - "docker build --target base -t ${ECR_NAMESPACE}:${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_COMMIT}-base ${DOCKERFILE_LOCATION}"
      - 'echo "--- :docker: Run PHP_CodeSniffer Linting"'
      - "docker run --rm ${ECR_NAMESPACE}:${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_COMMIT}-base composer phpcs"
